name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_927cb67d-ea81-4670-878c-10d238a6dc7c }}
          GH_TOKEN: ${{ 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 }}
